[tool.poetry]
name = "flockwave-net"
version = "1.0.2"
description = "Networking related functions for apps based on the Flockwave framework"
authors = ["Tamas Nepusz <tamas@collmot.com>"]
packages = [
    { include = "flockwave", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.7"
netifaces = ">=0.11.0"
trio = { version = "^0.19.0", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
pytest-trio = "^0.6.0"
pytest-cov = "^2.10.0"
coverage = {extras = ["toml"], version = "^5.2"}

[tool.poetry.extras]
async = ["trio"]

[[tool.poetry.source]]
name = "collmot"
url = "https://pypi.collmot.com/simple/"

[tool.coverage.paths]
source = ["src"]

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
